source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Generic dependencies
gem 'mimemagic', '~> 0.4.3'
gem 'rails', '~> 6.1', '>= 6.1.4.1'
gem 'pg'
gem 'puma', '~> 5.5', '>= 5.5.2'
gem 'bootsnap', '~> 1.9', '>= 1.9.1', require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'rufus-scheduler'

############################
#  S  E  R  V  I  C  E  S  #
############################
gem 'github_api', '~> 0.19.0'
gem 'discordrb', '~> 3.4'
gem 'rss'

# JWT auth dependencies
gem 'rack-cors'
gem 'bcrypt'
gem 'jwt'

# Misc dev dependencies
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end